# Generated by Django 3.2.16 on 2023-01-26 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0002_data_migration"),
    ]

    operations = []
