# Generated by Django 3.2.16 on 2023-01-26 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mainapp", "0003_data_migration"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="courseteachers",
            name="course",
        ),
        migrations.RemoveField(
            model_name="lesson",
            name="course",
        ),
        migrations.DeleteModel(
            name="News",
        ),
        migrations.DeleteModel(
            name="CourseTeachers",
        ),
        migrations.DeleteModel(
            name="Lesson",
        ),
    ]
